:sparkles: :white_check_mark: Pruebas caja negra en 'calculator_roc_class.R'
IslasGECI/dimorfismo pull request #26
Opened 2020-09-23 22:14 UTC by andrea-sanchez

- [Repositorio: Dimorfismo](https://github.com/IslasGECI/dimorfismo)

# Requisitos

## [Implementación en R](https://github.com/IslasGECI/manual#implementaci%C3%B3n-en-r)

- [ ] Corre una prueba dummy con testthat en GitHub Actions
- [ ] Realiza análisis estático (despeluza) con lintr en GitHub Actions

## [Pruebas de R](https://github.com/IslasGECI/manual#pruebas-de-r)
- [ ] Se verifica manualmente la resistencia de las pruebas a mutaciones en `calculator_ROC_class.R`

2020-09-30 00:28 UTC, evaristor commented on Dockerfile
> +RUN Rscript -e "install.packages(c('covr', 'lintr', 'rjson', 'roxygen2', 'testthat', 'styler'), repos='http://cran.rstudio.com')"
¿Por favor podrías ordenarlos alfabéticamente?:

```suggestion
RUN Rscript -e "install.packages(c('covr', 'lintr', 'rjson', 'roxygen2', 'styler', 'testthat'), repos='http://cran.rstudio.com')"
```

2020-10-01 01:30 UTC, evaristor requested changes

2020-10-01 01:30 UTC, evaristor commented on Makefile
> +	rm --force --recursive man
Por favor podrías ordenar esto alfabéticamente?

2020-10-01 01:30 UTC, evaristor commented on Makefile
> +
Pareciera que este código lo ejecutamos un única vez. (A diferencia de `runLint` que lo usamos dos veces.) Yo creo que no vale la pena refactorizar antes de tiempo ya que sólo incrementa la complejidad sin agregar legibilidad.

```suggestion
```

2020-10-01 01:30 UTC, evaristor commented on Makefile
> +	$(runStyler)
Pareciera que `runStyler` lo usas una única vez. En este caso lo óptimo es declararlo como _phony_ ya que no hay código repetido.

```suggestion
	R -e "library(styler)" \
	  -e "style_dir('src')" \
	  -e "style_dir('tests')" \
	  -e "style_dir('R')"
```

2020-10-01 20:34 UTC, evaristor commented on Makefile
> +	  -e "style_dir('tests')"
Así me gustó más :+1:

2020-10-02 09:23 UTC, andrea-sanchez commented
Alguna idea de porqué ningún `commit` de este **_pull_** **_request_** se reflejó  en mi atesorado tablero de contribuciones? :crying_cat_face:

2020-10-02 16:25 UTC, evaristor commented
> Alguna idea de porqué ningún `commit` de este **_pull request_** se reflejó en mi atesorado tablero de contribuciones?

Se mostrarán de manera retroactiva cuando aprobemos el PR. Creo que deben estar en la rama principal (`default` en nuestro caso) para que te cuenten.

2020-10-07 16:50 UTC, nepito requested changes
Hola @andrea-sanchez estás haciendo magia con este repor ( :mage_man: ), te está quedando a todo dar. Aquí te dejo mis comentarios.

2020-10-07 16:50 UTC, nepito commented on tests/testthat/tests_02_evaluate_better_models.R
> +  expect_equal(length(readLines(json_data_path)), 43)
Intentamos darle la misma importacnia a las pruebas como al código que las hará pasar. Así las mismas buenas constumbres de programación que aplicamos al código deberemos aplicar a las pruebas. 

Por favor encapsula (mete en una variable) el número mágico y la "ruda" expresión `length(readLines(json_data_path))`, para que se vea algo así:
```suggestion
  expect_equal(obtained_length, expected_length)
```
Creo que esas variables las puedes definir justo antes de la prueba, en la línea 17, pero si puedes hacerlo dentro del `test_that` quedará mejor. Es decir si se ve algo así:
```
test_that("Los resultados generados del código son correctos y siguen la guía de estilo:", {
  obtained_length <- length(readLines(json_data_path))
  expected_length <- 43
  expect_equal(json_data, json_correct_data)
```
mejor.

2020-10-07 16:50 UTC, nepito commented on tests/testthat/tests_calculator_roc_class.R
> +  expect_equal(calculator_roc$best_threshold_error(fake_data_to_test)$"threshold"[1], 0.505)
Por favor encapsula en una variable el número mágico y el umbral obtenido. La prueba cambiaría a algo así:
```suggestion
  obtained_threshold <- calculator_roc$best_threshold_error(fake_data_to_test)$"threshold"[1]
  expected_threshold <- 0.505
  expect_equal(obtained_threshold, expected_threshold)
```

2020-10-07 16:50 UTC, nepito commented on src/normalize_function.R
> +  return(normalize_return)
¿Qué pasa cuando le quitas el `return`? ¿truena algo?
```suggestion
```

2020-10-09 10:19 UTC, andrea-sanchez commented on src/normalize_function.R
> +  return(normalize_return)
Nope, no truena nada, pero, por el momento no quisiera eliminarlo. En las líneas 23-26 de la clase `dimorphism_model`, se utiliza la misma función y, aún, no estoy segura cuál me conviene conservar y cuál eliminar :smile_cat:

**Sidenote** : No estoy segura porque no sé cómo acceder a una función dentro de un método (tirando la loquera, algo tipo normalized_data$predict$normalize ) y además tendría que declarar como objeto `normalized_data` en `01_create_parameter_logistic_model_LAAL.R` (línea 90). En caso contrario, eliminó la función de `dimorphism_model_class.R` y me quedo con `normalize_function.R`. 

Estoy casi segura que no me doy a enteder jaja pero si quieres en un :tomato: te comparto mi idea

2020-10-09 16:08 UTC, nepito commented on src/normalize_function.R
> +  return(normalize_return)
Tienes toda la razón del mundo :raised_hands: (será mejor en un :tomato: ). Pero te adelanto un poco. Según la verdadera deidad en R (y hombre más guapo en la programación) no es necesario escribir `return` en todas las funciones. Si lo que quieres regresar es la última variable que asignaste, eso se hará de manera automática. [Aquí](https://style.tidyverse.org/functions.html#return) lo puedes ver. 

Con mucho gusto podemos tener el tomatuko para darnos a entender mejor.

2020-10-09 19:04 UTC, nepito requested changes
Te quedaron muy bonitas las pruebas, muchas felicidades :raised_hands: . Aquí te dejo un par de sugerencias.

2020-10-15 18:07 UTC, nepito requested changes
Hola @andrea-sanchez aquí te dejo una revisión :stuck_out_tongue_winking_eye:

2020-10-15 18:07 UTC, nepito commented on tests/testthat/tests_02_evaluate_better_models.R
> +  expect_equal(outcome_length_json, expected_length)
Esto dice el tío Bob:
>Variables and functions should be defined close to where they are used. Local variables should be declared **just above** their first usage and should have a small vertical scope. We don’t want local variables declared hundreds of lines distant from their usages. 
(El subrayado es mío) 

Si seguimos su recomendación aquí veríamos algo así: 
```suggestion
  csv_correct_data <- data.table(read.csv(csv_correct_data_path))
  csv_data <- data.table(read.csv(csv_data_path))
  expect_equal(csv_data, csv_correct_data)
  json_correct_data <- rjson::fromJSON(file = json_correct_data_path)
  json_data <- rjson::fromJSON(file = json_data_path)
  expect_equal(json_data, json_correct_data)
  expected_length <- 43
  obtained_length <- length(readLines(json_data_path))
  expect_equal(obtained_length, expected_length)
  outcome_length_json <- length(readLines(json_data_dir))
  expect_equal(outcome_length_json, expected_length)
```
Por favor prueba la sugerencia del tío Bob, para ver si ganamo legibilidad.

2020-10-20 23:08 UTC, nepito requested changes

2020-10-20 23:08 UTC, nepito commented on src/01_create_parameter_logistic_model_LAAL.R
Este archivo es de 243 líneas y me gustaría que ahora lo tratáramos de hacer de unas 50 líneas, así que te iré proponiendo unos poquitos de cambios. Por ejemplo me gustaría hacer tres funciones una (la tercera a la que llamaré `fit_step_regration`) implementará las otras dos (a las que llamaré `fit_null_model` y `fit_completed_model`). 

Así me imagino que podríamos cambiar las [líneas 106-113](https://github.com/IslasGECI/dimorfismo/pull/26/files?file-filters%5B%5D=.R#diff-49847d3e5df40631cdfa2dcac0bda849931490a742ba4ce5472e26f26fdb26a3R106-R113) que ahora se ve así:
```
step_regression <- step(null_regression,
    scope = list(
      lower = null_regression,
      upper = all_regression
    ),
    direction = "both",
    trace = 0
  )
```
por algo más o menos así:
```
step_regression <- fit_step_regression(normalized_data)
```
y esa "hipotética" función me la imagino con la siguiente forma:
```
fit_step_regression <- function(normalized_data) {
  null_regression <- fit_null_regression(normalized_data)
  completed_regression <- fit_completed_regression(normalized_data)
  step_regression <- make_step_regression(null_regression, completed_regression)
}
```
 Y por último a la función `make_step_regression` con la forma:
```
make_step_regression <- function(null_regression, all_regression){
step(null_regression,
    scope = list(
      lower = null_regression,
      upper = all_regression
    ),
    direction = "both",
    trace = 0
  )
}
```

¿Qué te parece el borrador de propuesta? Claro que estaría ideal que esas funciones pudieran tener sus respectivas pruebas, pero eso solo es un ideal.

Por favor implementa la fucnión `fit_step_regression`.

2020-10-21 23:35 UTC, andrea-sanchez commented on src/01_create_parameter_logistic_model_LAAL.R
Muchísimas gracias por la propuesta @nepito . Te parece si la implementamos en una nueva rama /  _pull request_? Me gustaría que el contenido de esta rama entrada a la `develop` lo antes posible. 
Guardé esta sugerencia en [este _issue #27_](https://github.com/IslasGECI/dimorfismo/issues/27) :smiley_cat:

2020-10-22 15:54 UTC, nepito approved these changes
Excelente trabajo @andrea-sanchez

2020-10-22 15:54 UTC, merged