:sparkles: :white_check_mark: Pruebas caja negra en normalize_function.R
IslasGECI/dimorfismo pull request #30
Opened 2020-11-24 21:41 UTC by andrea-sanchez

- [Repositorio: Dimorfismo](https://github.com/IslasGECI/dimorfismo)

# Requisitos

## [Implementación en R](https://github.com/IslasGECI/manual#implementaci%C3%B3n-en-r)

- [ ] Corre una prueba dummy con testthat en GitHub Actions
- [ ] Realiza análisis estático (despeluza) con lintr en GitHub Actions

## [Pruebas de R](https://github.com/IslasGECI/manual#pruebas-de-r)
- [ ] Se verifica manualmente la resistencia de las pruebas a mutaciones en `normalize_function.R`

[Andrea: No tocar](https://app.gitkraken.com/glo/board/5f8efd0f6ddf5200112cb681/card/5fbd6af4d4b7f400112ba0a5)

2020-12-01 18:06 UTC, nepito requested changes
Recuerdo que ya me explicaste pero no recuerdo qué me dijiste así que volveré a preguntar.
¿Por qué usamos de dos maneras distintas esta función? ¿Por qué no utilizamos equella en la que solo usa un parámetro? (y calculamos el `max` y el `min` siempre dentro de la función).

2020-12-01 18:06 UTC, nepito commented on tests/testthat/tests_normalize_function.R
> +    min_test_data <- 100
¿qué te parece poner la operación de manera explícita?
```suggestion
    max_test_data <- max(test_data)
    min_test_data <- min(test_data)
```

2020-12-01 20:20 UTC, andrea-sanchez commented
Halloooo @nepito ! Hay veces en que el `max` y el `min` se leen de un `csv`, otras veces donde las aporta un método privado y veces donde sólo te da una columna de valores y te dice "hazle como puedas :v: " jaja. 

> Recuerdo que ya me explicaste pero no recuerdo qué me dijiste así que volveré a preguntar.
> ¿Por qué usamos de dos maneras distintas esta función? ¿Por qué no utilizamos equella en la que solo usa un parámetro? (y calculamos el `max` y el `min` siempre dentro de la función).

2020-12-01 20:23 UTC, nepito commented
> Halloooo @nepito ! Hay veces en que el `max` y el `min` se leen de un `csv`, otras veces donde las aporta un método privado y veces donde sólo te da una columna de valores y te dice "hazle como puedas  " jaja.
> 
> > Recuerdo que ya me explicaste pero no recuerdo qué me dijiste así que volveré a preguntar.
> > ¿Por qué usamos de dos maneras distintas esta función? ¿Por qué no utilizamos equella en la que solo usa un parámetro? (y calculamos el `max` y el `min` siempre dentro de la función).

No es sugerencia sino una pregunta: ¿será mucho problema hacer que siempre las tome de los datos? Que siempre sea un "hazle como puedas".

2020-12-01 20:49 UTC, andrea-sanchez commented
:rainbow: :rainbow: :rainbow: **Todo es posible con R**:rainbow: :rainbow: :rainbow: @nepito 
Pero, sería una función muy fea y rebuscada. Ni siquiera consideraría ese monstruote una función, sino casi casi un _script_ de casi 50 líneas completas. Un Frankestein :zombie_man:
Considero que, para este caso, es mejor dejarlo así, y que las clases y otras funciones que usan `normalize_function` la trabajen a su conveniencia.  
> No es sugerencia sino una pregunta: ¿será mucho problema hacer que siempre las tome de los datos? Que siempre sea un "hazle como puedas".
> > Halloooo @nepito ! Hay veces en que el `max` y el `min` se leen de un `csv`, otras veces donde las aporta un método privado y veces donde sólo te da una columna de valores y te dice "hazle como puedas  " jaja.
> > > Recuerdo que ya me explicaste pero no recuerdo qué me dijiste así que volveré a preguntar.
> > > ¿Por qué usamos de dos maneras distintas esta función? ¿Por qué no utilizamos equella en la que solo usa un parámetro? (y calculamos el `max` y el `min` siempre dentro de la función).

2020-12-01 21:09 UTC, MaritzaB requested changes
Holi @andrea-sanchez, te dejé unos comentarios en el datapackage.json
Uno último que no encontré dónde poner es si por favor le puedes agregar como metadato de tabla la descripción de esta. Recuerda que los metadatos de tabla son los siguientes:
```
{
            "name": "morfometria_albatros-laysan_guadalupe",
            "description": "Morfometría de albatros de Laysan en Isla Guadalupe (2015-2016)",
            "encoding": "utf-8",
            "format": "csv",
            "mediatype": "text/csv",
            "path": "laysan_albatross_morphometry_guadalupe.csv",
            "profile": "tabular-data-resource",
            "source": "Medidas in situ",
            "title": "Laysan Albatross morphometry from Guadalupe Island",
            "titulo": "Morfometría de Albatros de Laysan en Isla Guadalupe",
            "schema": {
```

Tal vez podríamos ponerlo despues del "titulo".

2020-12-01 21:09 UTC, MaritzaB commented on data/raw/datapackage.json
>                          "units": "mm",
En la descripción de los campos hay algunas palabras que están en mayusculas sin ser nombres propios o emepzar en oración, como:

> "description": "Distancia en milímetros entre la punta del pico hasta el curvatura craneal respecto al plano **S**agital del **A**ve"

¿Podrías por favor cambiar las mayúsculas por minúsculas en todos los campos donde aplique?

2020-12-01 21:09 UTC, MaritzaB commented on data/raw/datapackage.json
>                          "units": "mm",
Podrías por favor uniformizar los constraints para que queden de la siguiente manera:
```
         "constraints": {
                            "minimum": 100.8 ,
                            "maximum": 119.49
                        }
```

2020-12-02 23:19 UTC, MaritzaB requested changes
Hola @andrea-sanchez que buen _trapazo_ le estas dando a este archivo.
Te dejo unos comentarios 😉 .

2020-12-02 23:19 UTC, MaritzaB commented on data/raw/datapackage.json
>                          "nombre_largo": "Darvic",
```suggestion
                        "long_name": "Darvic id",
                        "nombre_largo": "Id del Darvic",

```

2020-12-02 23:19 UTC, MaritzaB commented on data/raw/datapackage.json
> +                        "description": "Sexo del albatros de Laysan extraído por medio sanguineo donde H representa a hembras y M a machos.",
```suggestion
                        "description": "Sexo del albatros de Laysan determinado por medio sanguineo. Nomenclatura: H-Hembras y M-Machos.",

```

2020-12-02 23:19 UTC, MaritzaB commented on data/raw/datapackage.json
> +                        "description": "Información revelante y adional proporcionada."
Creo que aquí también podemos agregar un constraints de pattern. Sería uno sencillo, solo que verifique que hay una oración escrita. Esto lo empecé a implementar porque en ocasiones había espacios en blanco que no los encontraba el _goodtables_.

2020-12-02 23:19 UTC, MaritzaB commented on data/raw/datapackage.json
>                          "nombre_largo": "Peso",
En otras bases de datos hemos acordado que _masa_ es un nombre más adecuado para este tipo de dato. De igual forma, conviene ampliar la descripción de este campo.

2020-12-08 17:30 UTC, MaritzaB requested changes
Hola @andrea-sanchez . Aquí te dejo la segunda tanda de comentarios 😉 .

2020-12-08 17:30 UTC, MaritzaB commented on data/raw/datapackage.json
> +                        "description": "Colonia de distrubución interna de Isla Guadalupe.",
En general, la palabra isla la dejamos con minúsculas.
```suggestion
                        "description": "Colonia de distrubución interna de isla Guadalupe.",

```

2020-12-08 17:30 UTC, MaritzaB commented on data/raw/datapackage.json
> +                        "description": "Código de identificación de refugios de albatros de Laysan.",
```suggestion
                        "description": "Código de identificación del refugio de albatros de Laysan medido.",

```

2020-12-08 17:30 UTC, MaritzaB commented on data/raw/datapackage.json
> +                        "description": "Código de identificación representado en el anillo visible de cada albatros de Laysan",
```suggestion
                        "description": "Código de identificación representado en el anillo visible del individuo de albatros de Laysan",

```

2020-12-08 17:30 UTC, MaritzaB commented on data/raw/datapackage.json
> +                        "description": "Sexo del albatros de Laysan determinado por medio sanguineo. Nomenclatura: H-Hembras y M-Machos.",
Aquí no estoy segura que la palabra _método_ sea la adecuada, pero _medio_ se oye raro.
```suggestion
                        "description": "Sexo del albatros de Laysan determinado por método sanguineo. Nomenclatura: H-Hembras y M-Machos.",

```

2020-12-08 17:30 UTC, MaritzaB commented on data/raw/datapackage.json
>                          "name": "longitud_pico",
```suggestion
                        "name": "Longitud_pico",

```

2020-12-08 17:30 UTC, MaritzaB commented on data/raw/datapackage.json
>                          "name": "ancho_craneo",
```suggestion
                        "name": "Ancho_craneo",

```

2020-12-08 17:30 UTC, MaritzaB commented on data/raw/datapackage.json
> +                        "description": "Masa corporal del ave en medición.",
```suggestion
                        "description": "Masa corporal del individuo de albratros de Laysan.",

```

2020-12-08 17:30 UTC, MaritzaB commented on data/raw/datapackage.json
> +                        "description": "Información revelante y adional proporcionada.",
```suggestion
                        "description": "Información revelante y adicional proporcionada acerca de la medición.",

```

2020-12-08 21:23 UTC, andrea-sanchez commented on data/raw/datapackage.json
>                          "name": "ancho_craneo",
Hallooooo @MaritzaB Muchas gracias por las correcciones! :smile_cat: 
Pudiera dejar las variables en `snake_case`, me gusta cómo se ven ya dentro de **R** (donde también se usa `snake_case` para nombrar variables)? Según[ leí aquí](https://islasgeci.github.io/protocolo_basico/nomenclatura.html) no hay taaanta diferencia

2020-12-14 17:17 UTC, MaritzaB commented on data/raw/datapackage.json
>                          "name": "ancho_craneo",
Si, claro. Está bien, de hecho me confundí yo jaja. Pensé que estaban al revés, pero ya vi que no.

2020-12-14 17:32 UTC, MaritzaB requested changes
Pues prácticamente ya quedó @andrea-sanchez 🙌🏽 ! Solo te dejé un último comentario 🧐  y listo.

2020-12-14 17:32 UTC, MaritzaB commented on data/raw/datapackage.json
> +                        "description": "Colonia de distrubución interna de Isla Guadalupe.",
Holi @andrea-sanchez  en los constraints de enum, ¿puedes ordenar los campos alfabéticamente ✏️  por fis?

```
                        "enum": [
                                "Morro Prieto",
                                "Punta Sur",
                                "Zapato",
                            ]

```

2020-12-17 00:01 UTC, nepito approved these changes
Excelente trabajo @andrea-sanchez y @MaritzaB

2020-12-17 00:02 UTC, merged