👨🏽‍🎓Add new tests for didactic purpose
IslasGECI/dimorfismo pull request #42
Opened 2022-04-19 16:36 UTC by AlejandroPad

2022-04-21 20:07 UTC, AlejandroPad commented
Hola, @devarops @nepito. Cuando realizo en una terminal el comando `docker build --tag islasgeci .` me sale el siguiente error
![image](https://user-images.githubusercontent.com/70448418/164543655-62eee310-4bd1-4605-8d1f-bb6b930eeb5f.png)

2022-04-22 21:17 UTC, nepito commented
Hola @AlejandroPad aquí tenemos un muy buen avance :raised_hands: : queríamos que tronara el _actions_ y lo logramos:
![image](https://user-images.githubusercontent.com/35377740/164793575-a7af6e24-46b1-4579-b38c-c337a87cf1cf.png)
 ## El intento 365
 El primer cambio que hicimos fue agregar el documento `tests/testthat.R`. Con eso ya obtuvimos el error que queríamos. Es decir, este archivo nos permitió ver que la función tenía un nombre incorrecto:
 
![image](https://user-images.githubusercontent.com/35377740/164793884-7131c46b-f5a0-4a6d-bc8b-4cda6771004c.png)

## El intento 267
En el último cambio movimos el orden de cuando copiamos los archivo. Esta es la captura de pantalla que nos mandaste, es decir no encuentra los archivos. Esto sucede porque tratar instalar una el módulo paro los archivo no están:
![image](https://user-images.githubusercontent.com/35377740/164794135-fc18234e-abf1-4698-aa79-2c57221ae49e.png)

## Pendientes
- [ ] Regresa el repositorio al estados del intento 365, es decir cuando agregamos el archivo ` tests/testthat.R`
- [ ] Cambia el nombre de la función (o tal vez de las pruebas) para que ya no truenen las pruebas
- [ ] Verifica que todo está pasando como esperamos

2022-04-22 21:18 UTC, nepito requested changes
Hola @AlejandroPad parece que ya quedó lo que andamos buscando. 

## Pendientes
- [ ] Regresa el repositorio al estados del intento 365, es decir cuando agregamos el archivo ` tests/testthat.R`
- [ ] Cambia el nombre de la función (o tal vez de las pruebas) para que ya no truenen las pruebas
- [ ] Verifica que todo está pasando como esperamos

2022-05-03 06:04 UTC, AlejandroPad commented
![image](https://user-images.githubusercontent.com/70448418/166410606-6f0884e4-d5c1-4801-882c-8085f95deaf8.png)

Aquí al hacer `docker build --tag islasgeci .` ya no me manda errores, solo warnings.

2022-05-03 06:21 UTC, AlejandroPad commented
![image](https://user-images.githubusercontent.com/70448418/166411852-8fa9924e-05d1-4603-9480-179651c2ae5a.png)
Esto sale al hacer `docker run islasgeci make check`

2022-05-03 06:27 UTC, AlejandroPad commented
![image](https://user-images.githubusercontent.com/70448418/166412312-165df47e-34d4-4806-9866-261b81e905fe.png)
Esto sale al hacer `docker run islasgeci make coverage`

2022-05-03 15:56 UTC, nepito commented
## 3 de mayo
- Borramos todas las imágenes
- Hicimos `make clean` para borrarar todos los residuos
- Intentamos construir la imagen `docker build -t dimorfismo .`

2022-05-05 15:45 UTC, nepito commented
Con instalación del paquete de dimorfismo no podemos construir la imagen. Así que borramos la instalación. Con esto estamos apuntando a la dirección de hacer este repositorio de clase 1.

2022-05-05 21:48 UTC, nepito commented
@AlejandroPad, al objetivo `coverage` habrá que agregarle el requerimiento `install`:
![image](https://user-images.githubusercontent.com/35377740/167031099-6986272d-8764-4418-b6b9-697af221ddbe.png)

2022-05-05 21:51 UTC, AlejandroPad commented
@nepito Está raro ese error, en el ultimo ya lo puse.
![image](https://user-images.githubusercontent.com/70448418/167031300-4b37626d-9bcb-4285-9074-c20eb60e92e6.png)

2022-05-05 21:52 UTC, nepito requested changes
Ya vi que sí está el ingrediente, tal vez funcione si lo ponemos en otro orden.

2022-05-05 21:52 UTC, nepito commented on Makefile
> +coverage: $(jsonLogisticModelParameters) install
Intenta cambiando el orden de los requerimientos. Yo esperaría que e; orden no importara, pero tal vez sí.
```suggestion
coverage: install $(jsonLogisticModelParameters)
```

2022-05-05 22:45 UTC, nepito commented
Hola @AlejandroPad sí sirvió el cambio :raised_hands:  ahora truena más adelante. Por favor intenta correr de manera local ese objetivo.

2022-05-12 16:53 UTC, devarops commented
Nota al margen:

La instrucción `devtools::document()` genera el archivo `NAMESPACE` del cual dependemos.
¿Será que esta instrucción debería ser parte del _phony_ `install` en lugar de ser parte del _phony_ `check_install`?

![image](https://user-images.githubusercontent.com/3461018/168127859-6b070410-1fe1-418f-897d-0638f92c5af5.png)

2022-05-17 16:45 UTC, AlejandroPad commented
Encontramos un error en la linea 147 de `src/01_create_parameter_logistic_model_LAAL.R` la cual es: `prob <- dimorphism_model_albatross$predict(validation_data)`. 
```R
normalize_column = function(column, variable) {
      minimum <- private$get_minimum(variable)
      maximum <- private$get_maximum(variable)
      normalized_column <- as.data.frame(normalize(column, minimum, maximum))
      return(normalized_column)
    }
```

## 19/Mayo/2022
El nuevo error ya lo encontramos en la línea 37 en la función `calculate_z` 
```R
calculate_z = function(data_table, variable) {
      column <- data_table[, variable$Variables]
      normalized_column <- private$normalize_column(column, variable)
      private$z <- private$z + normalized_column * private$get_estimate_value(variable$Variables)
    }
```
`data.table[,variable$Variables]` no nos está regresando el valor esperado. Conjeturamos que no acepta una variable como argumento. Con tibbles logramos usar una variable como argumento.
Se agregó una línea en dicha función
```R
calculate_z = function(data_table, variable) {
      data_table = tibble(data_table)
      column <- data_table[, variable$Variables]
      normalized_column <- private$normalize_column(column, variable)
      private$z <- private$z + normalized_column * private$get_estimate_value(variable$Variables)
    }
```

2022-05-24 16:02 UTC, nepito commented
- ¿Qué hace `check_install`?
- ¿Por qué truena la receta del _coverage_?

2022-05-24 16:42 UTC, nepito commented
# 24/Mayo/2022
Cerramos el _pull request_ para tener limpio el nuevo con solo el material didáctico.

## Pendientes
- [ ] Prueba el ajuste de los `sintetic_data`
- [ ] Prueba el ajuste de los `sintetic_data2`
- [ ] Prueba el ajuste de los datos del titanic

2022-06-23 16:11 UTC, devarops approved these changes

2022-06-23 16:12 UTC, merged