⚗️ Modify variable and property names
IslasGECI/dimorfismo pull request #47
Opened 2022-09-21 17:46 UTC by AlejandroPad

Se cambió a inglés los nombres de las propiedades de `tests/data/logistic_model_parameters_tests.json`. Igualmente se detectó que al cambiarlas, surge un error en las pruebas con los valores esperados (al intentar hacer lo análogo en `data/processed/logistic_model_parameters.json` al correr las pruebas se vuelven a cambiar automaticamente a su forma Spanglish).

2022-09-26 18:33 UTC, devarops requested changes
Aquí te dejo unos comentarios

2022-09-26 18:33 UTC, devarops commented on data/raw/datapackage.json
> +                        "name": "close_brim_length",
```suggestion
                        "name": "closed_wing_length",

```

2022-09-26 18:33 UTC, devarops commented on data/raw/datapackage.json
> +                        "name": "open_brim_length",
```suggestion
                        "name": "opened_wing_length",

```

2022-09-26 18:33 UTC, devarops commented on data/raw/datapackage.json
> +                        "name": "media_wingspan",
```suggestion
                        "name": "half_wingspan",

```

2022-09-26 18:33 UTC, devarops commented on data/raw/datapackage.json
> +                        "nombre_largo": "Media wingspan",
```suggestion
                        "nombre_largo": "Half wingspan",

```

2022-09-26 18:33 UTC, devarops commented on data/raw/datapackage.json
> +                        "nombre_largo": "wingspan",
```suggestion
                        "nombre_largo": "Wingspan",

```

2022-09-26 18:33 UTC, devarops commented on data/raw/datapackage.json
> +                        "nombre_largo": "tarsus",
```suggestion
                        "nombre_largo": "Tarsus",

```

2022-09-26 18:33 UTC, devarops commented on data/raw/datapackage.json
> +                        "name": "beak_height",
```suggestion
                        "name": "bill_height",

```

2022-09-26 18:33 UTC, devarops commented on data/raw/datapackage.json
> +                        "name": "beak_length",
```suggestion
                        "name": "bill_length",

```

2022-09-26 18:33 UTC, devarops commented on data/raw/datapackage.json
>                          "long_name": "Cranial length",
```suggestion
                        "long_name": "Skull length",

```

2022-09-26 18:47 UTC, devarops commented on data/raw/datapackage.json
>                          "long_name": "Bill height",
```suggestion
                        "long_name": "Bill depth",

```

2022-09-26 18:48 UTC, devarops commented on data/raw/datapackage.json
> +                        "name": "skull_length",
```suggestion
                        "name": "head_length",

```

2022-09-26 18:48 UTC, devarops commented on data/raw/datapackage.json
> +                        "name": "skull_width",
```suggestion
                        "name": "head_width",

```

2022-09-26 18:48 UTC, devarops commented on data/raw/datapackage.json
>                          "long_name": "Craneal width",
```suggestion
                        "long_name": "Head width",

```

2022-09-26 18:49 UTC, devarops commented on data/raw/datapackage.json
> +                        "name": "close_brim_length",
```suggestion
                        "name": "closed_wing_length",

```

2022-09-29 18:00 UTC, devarops requested changes
¿Te están corriendo las pruebas con estos conflictos de _merge_?

2022-09-29 18:00 UTC, devarops commented on tests/testthat/tests_01_create_parameter_logistic_model_LAAL.R
> +>>>>>>> Stashed changes
Aquí tienes conflictos de _merge_. Debes resolverlos.

2022-09-29 18:00 UTC, devarops commented on src/01_create_parameter_logistic_model_LAAL.R
> +=======
Aquí tienes conflictos de _merge_. Debes resolverlos.

2022-09-29 18:00 UTC, devarops commented on src/01_create_parameter_logistic_model_LAAL.R
> +>>>>>>> Stashed changes
Aquí tienes conflictos de _merge_. Debes resolverlos.

2022-11-07 16:45 UTC, mvillasante reviewed
LGTM

2022-11-07 16:47 UTC, AlejandroPad commented
🔀🐤 Cambia nombre de variables
- [x] Cambiamos a inglés los nombres de las propiedades de `tests/data/logistic_model_parameters_tests.json`. 
- [x] Detectamos que al cambiarlas, surge un error en las pruebas con los valores esperados (al intentar hacer lo análogo en `data/processed/logistic_model_parameters.json` al correr las pruebas se vuelven a cambiar automaticamente a su forma Spanglish). 
- [x] Probar con otro json file generado con los datos de prueba
## Hecho
- Extrajimos la función `get_best_json_for_logistic_model` 
- Factorizamos funciones pequeñas en `get_best_json_for_logistic_model`
## Pendientes
- [ ] Eliminar json de la receta de los tests en `Makefile`
- [ ] Extraer funciones de los `src`

2022-11-07 16:48 UTC, merged